// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmflxwwcixgttlxphumx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtZmx4d3djaXhndHRseHBodW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjY3OTMsImV4cCI6MjA3MzI0Mjc5M30.d2hz7g-lXWuxbCwawExVhXes-Y4jyhvqJGT02J3_W6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});